BugTracking/urls.py
from django.contrib import admin
from django.urls import path
from bugapp.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('login-user', login_user, name='login_user'),
    path('logout-user', logout_user, name='logout_user'),
    path('add-new-bug', add_new_bug, name='add_new_bug'),
    path('add-new-project', add_new_project, name='add_new_project'),
    path('add-new-user', add_new_user, name='add_new_user'),
    path('bug-report', bug_report, name='bug_report'),
    path('project-report', project_report, name='project_report'),
    path('user-report', user_report, name='user_report'),
    path('change-password', Change_Password, name='Change_Password'),
    path('profile', profile, name='profile'),
    path('edit-user/<int:pid>', edit_user, name='edit_user'),
    path('delete-user/<int:pid>', delete_user, name='delete_user'),
    path('edit-project/<int:pid>', edit_project, name='edit_project'),
    path('delete-project/<int:pid>', delete_project, name='delete_project'),
    path('edit-bug/<int:pid>', edit_bug, name='edit_bug'),
    path('delete-bug/<int:pid>', delete_bug, name='delete_bug'),
    path('bug-detail/<int:pid>', bug_detail, name='bug_detail'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bugapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
USERROLE = ((1, "Manager"), (2, "Tester"), (3, "Developer"), (4, 'Admin'))

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    userrole = models.IntegerField(choices=USERROLE, null=True, blank=True, default=0)
    contact = models.CharField(max_length=100, null=True, blank=True)
    department = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.user.username

class Project(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    submission_date = models.DateTimeField(null=True, blank=True)
    duration = models.CharField(max_length=200, null=True, blank=True)
    client_name = models.CharField(max_length=200, null=True, blank=True)
    client_address = models.CharField(max_length=200, null=True, blank=True)
    phone_number = models.CharField(max_length=200, null=True, blank=True)
    email_id = models.CharField(max_length=200, null=True, blank=True)
    department_name = models.CharField(max_length=200, null=True, blank=True)
    project_lead = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True, related_name='project_lead')
    description = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

BUGSTATUS = ((1, 'Open'), (2, 'Close'), (3, 'In Progress'))
BUGTYPE = ((1, 'High Priority'), (2, 'Low Priority'), (3, 'Information'))
class Bug(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True, related_name='project')
    creator = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True, related_name='creator')
    assign_by = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True, related_name='assign_by')
    assign_to = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True, related_name='assign_to')
    title = models.CharField(max_length=200, null=True, blank=True)
    priority = models.CharField(max_length=200, null=True, blank=True)
    bug_level = models.CharField(max_length=200, null=True, blank=True)
    tester_code = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.IntegerField(choices=BUGSTATUS, null=True, blank=True, default=0)
    bug_type = models.IntegerField(choices=BUGTYPE, null=True, blank=True, default=0)
    file = models.FileField(null=True, blank=True)
    created = models.DateTimeField(null=True, auto_now_add=True, blank=True)
    updated = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    bug = models.ForeignKey(Bug, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=100, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.bug.title

bugapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout, login
from django.contrib import messages
from .models import *
# Create your views here.

def home(request):
    return render(request, 'home.html')


def login_user(request):
    if request.method == "POST":
        uname = request.POST['name']
        pwd = request.POST['password']
        user = authenticate(username=uname, password=pwd)
        if user:
            login(request, user)
            messages.success(request, "Login Successfully")
            return redirect('home')
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    messages.success(request, "Logout Successfully")
    return redirect('home')

def add_new_bug(request):
    if request.method == "POST":
        name = request.POST['name']
        project = request.POST['project']
        tester_code = request.POST['tester_code']
        bug_date = request.POST['bug_date']
        bug_level = request.POST['bug_level']
        bug_priority = request.POST['bug_priority']
        bug_type = request.POST['bug_type']
        status_name = request.POST['status_name']
        description = request.POST['description']
        proj_obj = Project.objects.get(id=project)
        creator = UserProfile.objects.get(user=request.user)
        bug = Bug.objects.create(title=name, description=description, project=proj_obj, creator=creator, status=status_name, bug_type=bug_type, created=bug_date, priority=bug_priority, bug_level=bug_level, tester_code=tester_code)
        messages.success(request, "Added Successfully")
        return redirect('bug_report')
    project = Project.objects.all()
    return render(request, 'add_new_bug.html', {'project': project, 'bug_type': BUGTYPE, 'bug_status': BUGSTATUS})

def add_new_project(request):
    if request.method == "POST":
        project_name = request.POST['project_name']
        project_duration = request.POST['project_duration']
        submission_date = request.POST['submission_date']
        client_name = request.POST['client_name']
        client_address = request.POST['client_address']
        phone_number = request.POST['phone_number']
        email = request.POST['email']
        department_name = request.POST['department_name']
        project_lead = request.POST['project_lead']
        description = request.POST['description']
        proj_lead = UserProfile.objects.get(id=project_lead)
        bug = Project.objects.create(name=project_name, description=description, submission_date=submission_date, duration=project_duration, client_name=client_name, client_address=client_address, phone_number=phone_number, email_id=email, department_name=department_name, project_lead=proj_lead)
        messages.success(request, "Added Successfully")
        return redirect('project_report')
    project = Project.objects.all()
    user = UserProfile.objects.all()
    return render(request, 'add_new_project.html', {'project': project, 'user': user})

def add_new_user(request):
    if request.method == "POST":
        userrole = request.POST['userrole']
        user_name = request.POST['user_name']
        # confirm = request.POST['confirm']
        password = request.POST['password']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        phone_number = request.POST['phone_number']
        gender = request.POST['gender']
        file = request.FILES['file']
        address = request.POST['address']
        dob = request.POST['dob']
        user = User.objects.create_user(username=user_name, first_name=first_name, last_name=last_name, password=password, email=email)
        bug = UserProfile.objects.create(user=user, userrole=userrole, contact=phone_number, gender=gender, file=file, address=address, dob=dob)
        messages.success(request, "Added Successfully")
        return redirect('user_report')
    return render(request, 'add_new_user.html', {'userrole': USERROLE})

def bug_report(request):
    bug = Bug.objects.all()
    return render(request, 'bug_report.html', {'bug': bug})

def project_report(request):
    project = Project.objects.all()
    return render(request, 'project_report.html', {'project': project})


def user_report(request):
    user = UserProfile.objects.all()
    return render(request, 'user_report.html', {'user': user})

@login_required(login_url="login")
def Change_Password(request):
    if request.method=="POST":
        n = request.POST['pwd1']
        c = request.POST['pwd2']
        o = request.POST['pwd3']
        if c == n:
            u = User.objects.get(username__exact=request.user.username)
            u.set_password(n)
            u.save()
            messages.success(request, "Changed Successfully")
            logout(request)
            return redirect('home')
        else:
            messages.success(request, "Password not matching")
    return render(request, 'change_password.html')

def profile(request):
    data = UserProfile.objects.get(user=request.user)
    if request.method == "POST":
        userrole = request.POST['userrole']
        user_name = request.POST['user_name']
        # confirm = request.POST['confirm']
        # password = request.POST['password']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        phone_number = request.POST['phone_number']
        gender = request.POST['gender']
        address = request.POST['address']
        dob = request.POST['dob']
        user = User.objects.filter(username=user_name).update(first_name=first_name, last_name=last_name, email=email)
        bug = UserProfile.objects.filter(user=user).update(userrole=userrole, contact=phone_number, gender=gender, address=address, dob=dob)
        try:
            file = request.FILES['file']
            UserProfile.objects.filter(user=user).update(file=file)
        except:
            pass
        messages.success(request, "Updated Successfully")
        return redirect('profile')
    return render(request, 'profile.html', {'data': data, 'userrole': USERROLE})

def edit_user(request,pid):
    data = UserProfile.objects.get(id=pid)
    if request.method == "POST":
        userrole = request.POST['userrole']
        user_name = request.POST['user_name']
        # confirm = request.POST['confirm']
        # password = request.POST['password']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        phone_number = request.POST['phone_number']
        gender = request.POST['gender']
        address = request.POST['address']
        dob = request.POST['dob']
        user = User.objects.filter(username=user_name).update(first_name=first_name, last_name=last_name, email=email)
        bug = UserProfile.objects.filter(user=user).update(userrole=userrole, contact=phone_number, gender=gender, address=address, dob=dob)
        try:
            file = request.FILES['file']
            UserProfile.objects.filter(user=user).update(file=file)
        except:
            pass
        messages.success(request, "Updated Successfully")
        return redirect('user_report')
    return render(request, 'edit_user.html', {'data': data, 'userrole': USERROLE})

def delete_user(request, pid):
    data = UserProfile.objects.get(id=pid)
    data.delete()
    messages.success(request, "Deleted Successfully")
    return redirect('user_report')

def edit_project(request,pid):
    data = Project.objects.get(id=pid)
    if request.method == "POST":
        project_name = request.POST['project_name']
        project_duration = request.POST['project_duration']
        submission_date = request.POST['submission_date']
        client_name = request.POST['client_name']
        client_address = request.POST['client_address']
        phone_number = request.POST['phone_number']
        email = request.POST['email']
        department_name = request.POST['department_name']
        project_lead = request.POST['project_lead']
        description = request.POST['description']

        proj_lead = UserProfile.objects.get(id=project_lead)
        bug = Project.objects.filter(id=pid).update(name=project_name, description=description, submission_date=submission_date,
                                     duration=project_duration, client_name=client_name, client_address=client_address,
                                     phone_number=phone_number, email_id=email, department_name=department_name,
                                     project_lead=proj_lead)
        messages.success(request, "Updated Successfully")
        return redirect('project_report')
    user = UserProfile.objects.all()
    return render(request, 'edit_project.html', {'data': data, 'user': user})

def delete_project(request, pid):
    data = Project.objects.get(id=pid)
    data.delete()
    messages.success(request, "Deleted Successfully")
    return redirect('project_report')

def edit_bug(request,pid):
    data = Bug.objects.get(id=pid)
    if request.method == "POST":
        name = request.POST['name']
        project = request.POST['project']
        tester_code = request.POST['tester_code']
        bug_date = request.POST['bug_date']
        bug_level = request.POST['bug_level']
        bug_priority = request.POST['bug_priority']
        bug_type = request.POST['bug_type']
        status_name = request.POST['status_name']
        description = request.POST['description']
        proj_obj = Project.objects.get(id=project)
        creator = UserProfile.objects.get(user=request.user)
        bug = Bug.objects.filter(id=pid).update(title=name, description=description, project=proj_obj, creator=creator,
                                 status=status_name, bug_type=bug_type, created=bug_date, priority=bug_priority,

bugapp/templates/add_new_bug.html
py{% extends 'index.html' %}
{% load static %}
{% block body %}

<main id="main">
    <!-- ======= Contact Section ======= -->
    <section id="login" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Add New Bug</h2>
          <h3><span>Add New Bug</span></h3>
<!--          <p>Add New Bug - Poetry - Stories. Share your words with the world.</p>-->
        </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">

          <div class="col-lg-12">
            <form action="" method="post" role="form" class="php-email-form">
              {% csrf_token %}
              <div class="row">
                <div class="form-group">
                  <label>Bug Name</label>
                  <input type="text" name="name" class="form-control" id="name" placeholder="Bug Name" required>
                </div>

                <div class="form-group">
                    <label>Project</label>
                    <select name="project" class="form-control" id="project" required>
                        <option value="">Select Project</option>
                        {% for i in project %}
                        <option value="{{i.id}}">{{i.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label>Tester Code</label>
                  <input type="text" class="form-control" name="tester_code" id="tester_code" placeholder="Tester Code" required>
                </div>

                <div class="form-group">
                  <label>Bug Date</label>
                  <input type="date" class="form-control" name="bug_date" id="bug_date" placeholder="Bug Date" required>
                </div>

                <div class="form-group">
                  <label>Bug Level</label>
                  <input type="text" class="form-control" name="bug_level" id="bug_level" placeholder="Bug Level" required>
                </div>

                <div class="form-group">
                  <label>Bug Priority</label>
                  <input type="text" class="form-control" name="bug_priority" id="bug_priority" placeholder="Bug Priority" required>
                </div>

               <div class="form-group">
                  <label>Bug Type</label>
                  <select name="bug_type" class="form-control" id="bug_type" required>
                        <option value="">Select Bug Type</option>
                        {% for i in bug_type %}
                        <option value="{{i.0}}">{{i.1}}</option>
                        {% endfor %}
                  </select>
               </div>

              <div class="form-group">
                  <label>Status Name</label>
                  <select name="status_name" class="form-control" id="status_name" required>
                        <option value="">Select Status Name</option>
                        {% for i in bug_status %}
                            <option value="{{i.0}}">{{i.1}}</option>
                        {% endfor %}
                  </select>
               </div>

              <div class="form-group">
                  <label>Description</label>
                  <textarea type="text" class="form-control" name="description" id="description" placeholder="Bug Description" required></textarea>
              </div>
              </div>

              <div class="text-center"><button type="submit">Submit</button></div>
            </form>
          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->
{% endblock %}

bugapp/templates/add_new_project.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<main id="main">
    <!-- ======= Contact Section ======= -->
    <section id="login" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Add New Project</h2>
          <h3><span>Add New Project</span></h3>
<!--          <p>Add New Project - Poetry - Stories. Share your words with the world.</p>-->
        </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">

          <div class="col-lg-12">
            <form action="" method="post" role="form" class="php-email-form">
              {% csrf_token %}
              <div class="row">
                <div class="form-group">
                  <label>Project Name</label>
                  <input type="text" name="project_name" class="form-control" id="project_name" placeholder="Project Name" required>
                </div>

                <div class="form-group">
                  <label>Submission Date</label>
                  <input type="date" name="submission_date" class="form-control" id="submission_date" placeholder="Submission Date" required>
                </div>

                <div class="form-group">
                    <label>Project Duration</label>
                    <input type="text" name="project_duration" class="form-control" id="project_duration" placeholder="Project Duration" required>
                </div>
                <div class="form-group">
                    <label>Client Name</label>
                  <input type="text" class="form-control" name="client_name" id="client_name" placeholder="Client Name" required>
                </div>

                <div class="form-group">
                  <label>Client Address</label>
                  <input type="text" class="form-control" name="client_address" id="client_address" placeholder="Client Address" required>
                </div>

                <div class="form-group">
                  <label>Phone Number</label>
                  <input type="text" class="form-control" name="phone_number" id="phone_number" placeholder="Phone number" required>
                </div>

                <div class="form-group">
                  <label>Email Id</label>
                  <input type="email" class="form-control" name="email" id="email" placeholder="Email Id" required>
                </div>

               <div class="form-group">
                  <label>Department Name</label>
                  <select name="department_name" class="form-control" id="department_name" required>
                        <option value="">Select Department</option>
                        <option value="Java Development">Java Development</option>
                        <option value="Python Department">Python Department</option>
                        <option value="PHP Department">PHP Department</option>
                        <option value="Front End Department">Front End Department</option>
                  </select>
               </div>

              <div class="form-group">
                  <label>Project Lead</label>
                  <select name="project_lead" class="form-control" id="project_lead" required>
                        <option value="">Select Project Lead</option>
                        {% for i in user %}
                            <option value="{{i.id}}">{{i.user.username}}</option>
                        {% endfor %}
                  </select>
               </div>

              <div class="form-group">
                  <label>Description</label>
                  <textarea type="text" class="form-control" name="description" id="description" placeholder="Project Description" required></textarea>
              </div>
              </div>

              <div class="text-center"><button type="submit">Submit</button></div>
            </form>
          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->
{% endblock %}

bugapp/templates/bug_detail.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<main id="main" data-aos="fade-up">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Bug Details</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li><a href="portfolio.html">Bug</a></li>
            <li>Bug Details</li>
          </ol>
        </div>

      </div>
    </section><!-- Breadcrumbs Section -->

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-12">
            <div class="portfolio-info">
              <h3>Bug information</h3>
              <ul>
                <li><strong>Bug Title</strong>: {{data.title}}</li>
                <li><strong>UserEmail</strong>: {{data.creator.user.email}}</li>
                <li><strong>BUg Status date</strong>: {{data.get_status_display}}</li>
                <li><strong>Raise by</strong>: {{data.raise_by}}</li>
                <li><strong>Bug Type</strong>: {{data.get_bug_type_display}}</li>
              </ul>
            </div><hr>
            <div class="portfolio-description">
              <h2>Add Comment</h2>
              <div class="col-lg-12">
            <form action="" method="post" role="form" class="php-email-form">
{% csrf_token %}
                <div class="row">
                    <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" name="title" id="title" placeholder="Subject" required>
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" name="description" rows="5" placeholder="Message" required></textarea>
                    </div>
                </div>

              <div class="text-center"><button class="btn btn-primary pull-right" type="submit">Send Message</button></div>
            </form>
          </div>
            </div>
          </div>

        </div><hr>
          <h2>All Comment</h2>
          {% for i in comment %}
              <div  class="row gy-8" style="border:1px solid lightgray;padding:6px">
                  <div class="row" >
                      <div class="col-1">
                        <img class="card-img" src="{{i.user.file.url}}" alt="Card image"/>
                      </div>
                      <div class="col-6">
                        <div class="card-body-right">
                          <h5 class="card-title">{{i.title}}</h5><hr>
                          <p class="card-text">{{i.message}}</p>
                        </div>
                      </div>
                  </div>
              </div>
         {% endfor %}

      </div>
    </section><!-- End Portfolio Details Section -->

  </main>

{% endblock %}

bugapp/templates/bug_report.html
{% extends 'index.html' %}
{% load static %}
{% block body %}
  <link rel='stylesheet' type='text/css' href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
  <link rel='stylesheet' type='text/css' href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">

  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>

<script>
  $(document).ready(function() {
      $('#example').DataTable( {
          dom: 'Bfrtip',
          buttons: [
              'copyHtml5',
              'excelHtml5',
              'csvHtml5',
              'pdfHtml5'
          ]
      } );
  } );
</script>
<div class="container-fluid" style="width:90%;margin-top:8%">
                    <div class="container-fluid">
                        <h1 align="center" style="font-weight:bold;font-family : 'Monotype Corsiva' ; color : #E6120E ;margin-top:4%">View Bug Report</h1>
                         </div><hr>
                                <table id="example" class="display" style="width:100%">
                                  <thead>
                                    <tr>
                                      <th>#</th>
                                      <th>User Image</th>
                                      <th>Bug Title</th>
                                      <th>User Name</th>
                                      <th>Email</th>
                                      <th>Contact</th>
                                      <th>Type</th>
                                      <th>Status</th>
                                      <th>Action</th>

                                  </tr>
                              </thead>
                              <tbody>
                              {% for i in bug %}
                                <tr>
                                  <td>{{forloop.counter}}</td>
                                  <td>
                                      {% if i.creator.file %}
                                        <img src="{{i.creator.file.url}}" style="width:50px">
                                      {% endif %}
                                  </td>
                                  <td>{{i.title}}</td>
                                  <td>{{i.creator.user.username}}</td>
                                  <td>{{i.creator.user.email}}</td>
                                  <td>{{i.creator.contact}}</td>
                                  <td>

                                      <button class="btn {% if i.bug_type == 1 %}btn-danger{% elif i.bug_type == 2 %}btn-warning{% elif i.bug_type == 3 %}btn-info{% endif %}">{{i.get_bug_type_display}}</button>

                                  </td>
                                  <td>{{i.get_status_display}}</td>
                                  <td style="width:150px">
                                      <a href="/bug-detail/{{i.id}}"><button class="btn btn-info" ><i class="fa fa-eye"></i></button></a>
                                      <a href="/edit-bug/{{i.id}}"><button class="btn btn-primary"><i class="fa fa-edit"></i></button></a>
                                      <a href="/delete-bug/{{i.id}}"><button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i></button></a>
                                  </td>
                              </tr>
                              {% endfor %}
                          </tbody>
                      </table>
                  </div>
{% endblock %}

bugapp/templates/change_password.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

	<section class="logins py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="title-section mb-md-5 mb-4">
				<h6 class="w3ls-title-sub"></h6>
				<h3 class="w3ls-title text-uppercase text-dark font-weight-bold">Change Password</h3>
			</div><hr/>
			<div class="login px-sm-12" style="width:100%">
				<form action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-group row">
						<div class="col-md-12">
						<label>Old Password</label>
						<input type="password" class="form-control" name="pwd3" required="">
						</div>
					</div>
                  <div class="form-group row">
						<div class="col-md-12">
						<label>New Password</label>
						<input type="password" class="form-control" name="pwd1" required="">
						</div>
					</div>
                  <div class="form-group row">
						<div class="col-md-12">
						<label>Confirm Password</label>
						<input type="password" class="form-control" name="pwd2" required="">
						</div>
					</div>

					<button type="submit" class="btn btn-primary submit mt-4">Submit</button>
				</form>
			</div>
		</div>
	</section>
	<!-- //register -->

{% endblock %}